### ISSUE TITLE
test-runner.py error code translation needs to be OS aware

### ISSUE THREAD

**Issue by ThisDevDane** [ThisDevDane/Odin#1]
~~`just search man errno and take those, will get you pretty far.` - @oskarnp~~
`man sysexits`

**Comment by oskarnp** [comment]
Yeah, I meant sysexits. Caught my own mistake.

Here is some for macOS https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/sysexits.3.html

But then there is also a bunch defined by the shell, so Bash/Zsh etc. would have their own specific ones probably.

**Comment by ThisDrunkDane** [comment]
For linux I think we should only do `bash` it's the most common one and also the one that is used in the CI
